Testing pre-commit hook

diff --git a/git-hooks/pre-commit b/git-hooks/pre-commit
--- a/git-hooks/pre-commit
+++ b/git-hooks/pre-commit
@@ -1,6 +1,11 @@
 #!/bin/sh
-. "$(dirname "$0")/_/husky.sh"
 
-npm run test
-npx lint-staged
+# Run ESLint
+npm run lint
 
+# Check ESLint exit code
+if [ $? -ne 0 ]; then
+  echo ""
+  echo "ESLint errors or warnings found. Aborting commit."
+  exit 1
+fi
