Testing pre-commit hook

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,7 +1,19 @@
-#!/usr/bin/sh
+# #!/usr/bin/sh
 
 
-. "$(dirname "$0")/_/husky.sh"
+# . "$(dirname "$0")/_/husky.sh"
 
-npm run test
-npx lint-staged 
+# npm run test
+# npx lint-staged 
+
+#!/bin/sh
+
+# Run ESLint
+npm run lint
+
+# Check ESLint exit code
+if [ $? -ne 0 ]; then
+  echo ""
+  echo "ESLint errors or warnings found. Aborting commit."
+  exit 1
+fi
